name: localstack

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:4.6.0
    ports:
      - "4566:4566"# LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      #      - SERVICES=dynamodb,sqs,s3,sns
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - './localstack:/etc/localstack/init/ready.d:ro'
    networks:
      - localstack-network

networks:
  localstack-network:
    driver: bridge
